language: python
python:
 - "3.5"
install:
        - pip install pytest
        - pip install pytest-cov
        - pip install coveralls
script:
        - py.test coveralls/make test 
after_success:
        -coveralls
