language: python
python:
 - "3.5"
install:
        - pip install coveralls
        - pip install termcolor
script:
        - python3 -m unittest
        - coverage run -m unittest discover
after_success:
        coveralls

