language: python
python:
 - "3.5"
install:
        - pip install pytest
        - pip install pytest-cov
        - pip install coveralls
script:
        - python3 -m unittest
after_success:
        -coveralls
