language: python
python:
 - "3.5"
install:
        - pip install pytest
        - pip install pytest-cov
        - pip install coveralls
script:
        - make test
        - coverage run test_rpn.py
after_success:
        -coveralls
